// data/eletronicos.ts
export const eletronicos = [
  {
    nome: "iPhone 15 Pro Max",
    preco: 9999.99,
    descricao:
      "Smartphone da Apple com chip A17 Pro, câmera avançada e tela OLED de 6,7 polegadas.",
    estoque: 15,
    fabricante: "Apple",
    tipo: "Smartphone",
  },
  {
    nome: "Samsung Galaxy S24 Ultra",
    preco: 8999.99,
    descricao:
      "Smartphone Android com câmera de 200MP, tela AMOLED e S-Pen integrada.",
    estoque: 18,
    fabricante: "Samsung",
    tipo: "Smartphone",
  },
  {
    nome: "PlayStation 5",
    preco: 4499.99,
    descricao: "Console da Sony com suporte a jogos em 4K e SSD ultrarrápido.",
    estoque: 20,
    fabricante: "Sony",
    tipo: "Console",
  },
  {
    nome: "Xbox Series X",
    preco: 4299.99,
    descricao:
      "Console de última geração da Microsoft com 1TB de SSD e 12 teraflops de GPU.",
    estoque: 20,
    fabricante: "Microsoft",
    tipo: "Console",
  },
  {
    nome: "Nintendo Switch OLED",
    preco: 2499.99,
    descricao:
      "Console híbrido com tela OLED de 7 polegadas e Joy-Cons destacáveis.",
    estoque: 25,
    fabricante: "Nintendo",
    tipo: "Console",
  },
  {
    nome: 'Monitor LG UltraGear 27"',
    preco: 1999.99,
    descricao:
      "Monitor gamer com taxa de atualização de 144Hz e resolução QHD.",
    estoque: 10,
    fabricante: "LG",
    tipo: "Monitor",
  },
  {
    nome: "Notebook Dell XPS 13",
    preco: 7899.99,
    descricao:
      "Ultrabook com processador Intel i7 de 13ª geração e tela InfinityEdge.",
    estoque: 12,
    fabricante: "Dell",
    tipo: "Notebook",
  },
  {
    nome: "MacBook Air M3",
    preco: 8999.99,
    descricao: "Notebook da Apple com chip M3 e bateria de longa duração.",
    estoque: 8,
    fabricante: "Apple",
    tipo: "Notebook",
  },
  {
    nome: "Teclado Mecânico Redragon K552",
    preco: 249.99,
    descricao: "Teclado mecânico compacto com switches Outemu Blue.",
    estoque: 30,
    fabricante: "Redragon",
    tipo: "Acessório",
  },
  {
    nome: "Mouse Logitech G502 X",
    preco: 399.99,
    descricao: "Mouse gamer com sensor HERO 25K e 11 botões programáveis.",
    estoque: 30,
    fabricante: "Logitech",
    tipo: "Acessório",
  },
  {
    nome: "Headset HyperX Cloud II",
    preco: 599.99,
    descricao: "Fone de ouvido gamer com som surround 7.1 virtual.",
    estoque: 22,
    fabricante: "HyperX",
    tipo: "Acessório",
  },
  {
    nome: "Smartwatch Samsung Galaxy Watch 6",
    preco: 1599.99,
    descricao:
      "Relógio inteligente com monitoramento de saúde e integração com Android.",
    estoque: 17,
    fabricante: "Samsung",
    tipo: "Wearable",
  },
  {
    nome: "Kindle Paperwhite 11ª Geração",
    preco: 699.99,
    descricao: "Leitor digital com iluminação embutida e resistência à água.",
    estoque: 20,
    fabricante: "Amazon",
    tipo: "Leitor Digital",
  },
  {
    nome: "Tablet iPad Air M2",
    preco: 6499.99,
    descricao: "Tablet Apple com chip M2 e suporte ao Apple Pencil 2.",
    estoque: 10,
    fabricante: "Apple",
    tipo: "Tablet",
  },
  {
    nome: "Echo Dot 5ª Geração",
    preco: 379.99,
    descricao: "Alto-falante inteligente com Alexa integrada.",
    estoque: 35,
    fabricante: "Amazon",
    tipo: "Assistente Virtual",
  },
  {
    nome: "SSD Kingston NV2 1TB NVMe",
    preco: 429.99,
    descricao:
      "Unidade de estado sólido com leitura rápida para PCs e notebooks.",
    estoque: 40,
    fabricante: "Kingston",
    tipo: "Armazenamento",
  },
  {
    nome: "Placa de Vídeo RTX 4070 Super",
    preco: 4399.99,
    descricao: "GPU da NVIDIA para jogos em alta performance com Ray Tracing.",
    estoque: 5,
    fabricante: "NVIDIA",
    tipo: "Placa de Vídeo",
  },
  {
    nome: "Roteador TP-Link Archer AX73",
    preco: 699.99,
    descricao: "Roteador Wi-Fi 6 com velocidade até 5400 Mbps.",
    estoque: 16,
    fabricante: "TP-Link",
    tipo: "Rede",
  },
  {
    nome: "Câmera GoPro HERO12 Black",
    preco: 2499.99,
    descricao: "Câmera de ação com vídeo 5.3K e estabilização aprimorada.",
    estoque: 6,
    fabricante: "GoPro",
    tipo: "Câmera",
  },
  {
    nome: "Carregador MagSafe Apple",
    preco: 349.99,
    descricao: "Carregador sem fio magnético compatível com iPhones.",
    estoque: 28,
    fabricante: "Apple",
    tipo: "Acessório",
  },
];
