export const jogos = [
  {
    nome: "Final Fantasy VII Rebirth",
    preco: 299.99,
    descricao: "RPG de ação com gráficos impressionantes.",
    estoque: 50,
    desenvolvedora: "Square Enix",
    dataLancamento: new Date("2024-02-29"),
    plataforma: "PS5",
    generos: ["RPG", "Ação", "Fantasia"],
  },
  {
    nome: "Silent Hill 2 Remake",
    preco: 279.99,
    descricao: "Remake do clássico jogo de terror psicológico.",
    estoque: 40,
    desenvolvedora: "Bloober Team",
    dataLancamento: new Date("2024-10-20"),
    plataforma: "PS5",
    generos: ["Terror", "Ação"],
  },
  {
    nome: "Astro Bot",
    preco: 249.99,
    descricao: "Jogo de plataforma encantador para todas as idades.",
    estoque: 60,
    desenvolvedora: "Team Asobi",
    dataLancamento: new Date("2024-06-15"),
    plataforma: "PS5",
    generos: ["Plataforma", "Aventura"],
  },
  {
    nome: "Dragon Age: The Veilguard",
    preco: 299.99,
    descricao: "Novo capítulo da aclamada série de RPGs.",
    estoque: 45,
    desenvolvedora: "BioWare",
    dataLancamento: new Date("2024-09-10"),
    plataforma: "PC",
    generos: ["RPG", "Fantasia", "Aventura"],
  },
  {
    nome: "Helldivers 2",
    preco: 199.99,
    descricao: "Cooperativo de tiro em terceira pessoa.",
    estoque: 70,
    desenvolvedora: "Arrowhead Game Studios",
    dataLancamento: new Date("2024-03-08"),
    plataforma: "PS5",
    generos: ["Tiro", "Cooperativo", "Ação", "Sci-fi"],
  },
  {
    nome: "Black Myth: Wukong",
    preco: 289.99,
    descricao: "Aventura épica baseada na mitologia chinesa.",
    estoque: 55,
    desenvolvedora: "Game Science",
    dataLancamento: new Date("2024-08-19"),
    plataforma: "PC",
    generos: ["Ação", "Hack and Slash", "Fantasia"],
  },
  {
    nome: "Marvel Rivals",
    preco: 0.0,
    descricao: "Hero shooter multijogador com personagens da Marvel.",
    estoque: 100,
    desenvolvedora: "NetEase",
    dataLancamento: new Date("2024-12-01"),
    plataforma: "PS5",
    generos: ["Shooter", "Multijogador", "Gratuito para jogar"],
  },
  {
    nome: "Like a Dragon: Infinite Wealth",
    preco: 259.99,
    descricao: "Nova entrada na série Yakuza com narrativa envolvente.",
    estoque: 50,
    desenvolvedora: "Ryu Ga Gotoku Studio",
    dataLancamento: new Date("2024-11-05"),
    plataforma: "PS5",
    generos: ["JRPG", "RPG", "Ação"],
  },
  {
    nome: "Elden Ring: Shadow of the Erdtree",
    preco: 299.99,
    descricao: "Expansão do aclamado RPG de ação.",
    estoque: 60,
    desenvolvedora: "FromSoftware",
    dataLancamento: new Date("2024-07-22"),
    plataforma: "PC",
    generos: ["RPG", "Ação", "Expansão", "Fantasia"],
  },
  {
    nome: "Call of Duty: Black Ops 6",
    preco: 319.99,
    descricao: "Novo título da famosa franquia de tiro.",
    estoque: 80,
    desenvolvedora: "Treyarch",
    dataLancamento: new Date("2024-10-15"),
    plataforma: "PS5",
    generos: ["Tiro", "Ação", "Multijogador"],
  },
  {
    nome: "Prince of Persia: The Lost Crown",
    preco: 249.99,
    descricao: "Reinvenção do clássico jogo de plataforma.",
    estoque: 65,
    desenvolvedora: "Ubisoft",
    dataLancamento: new Date("2024-01-18"),
    plataforma: "PS5",
    generos: ["Plataforma", "Aventura", "Ação"],
  },
  {
    nome: "Tekken 8",
    preco: 279.99,
    descricao: "Oito entrada da renomada série de jogos de luta.",
    estoque: 70,
    desenvolvedora: "Bandai Namco",
    dataLancamento: new Date("2024-09-30"),
    plataforma: "PS5",
    generos: ["Luta", "Ação"],
  },
  {
    nome: "The Legend of Zelda: Echoes of Wisdom",
    preco: 299.99,
    descricao: "Nova aventura da princesa Zelda.",
    estoque: 50,
    desenvolvedora: "Nintendo",
    dataLancamento: new Date("2024-05-12"),
    plataforma: "Switch",
    generos: ["Aventura", "Fantasia", "RPG"],
  },
  {
    nome: "Star Wars Outlaws",
    preco: 289.99,
    descricao: "Aventura em mundo aberto no universo Star Wars.",
    estoque: 60,
    desenvolvedora: "Massive Entertainment",
    dataLancamento: new Date("2024-11-20"),
    plataforma: "PS5",
    generos: ["Mundo Aberto", "Aventura", "Sci-fi", "Ação"],
  },
  {
    nome: "Metaphor: ReFantazio",
    preco: 269.99,
    descricao: "RPG de fantasia dos criadores de Persona.",
    estoque: 55,
    desenvolvedora: "Studio Zero",
    dataLancamento: new Date("2024-08-05"),
    plataforma: "PS5",
    generos: ["JRPG", "Fantasia", "RPG"],
  },
  {
    nome: "Diablo IV: Vessel of Hatred",
    preco: 299.99,
    descricao: "Expansão sombria do RPG de ação.",
    estoque: 70,
    desenvolvedora: "Blizzard Entertainment",
    dataLancamento: new Date("2024-10-28"),
    plataforma: "PC",
    generos: ["RPG", "Ação", "Expansão"],
  },
  {
    nome: "Super Mario Party Jamboree",
    preco: 249.99,
    descricao: "Diversão garantida com minijogos para toda a família.",
    estoque: 80,
    desenvolvedora: "Nintendo",
    dataLancamento: new Date("2024-06-22"),
    plataforma: "Switch",
    generos: ["Party Game", "Multijogador", "Plataforma"],
  },
  {
    nome: "Frostpunk 2",
    preco: 259.99,
    descricao: "Sequência do aclamado jogo de sobrevivência e estratégia.",
    estoque: 50,
    desenvolvedora: "11 Bit Studios",
    dataLancamento: new Date("2024-09-14"),
    plataforma: "PC",
    generos: ["Estratégia", "Sobrevivência", "Simulação"],
  },
  {
    nome: "Stellar Blade",
    preco: 279.99,
    descricao: "Ação intensa em um mundo futurista.",
    estoque: 60,
    desenvolvedora: "Shift Up",
    dataLancamento: new Date("2024-07-08"),
    plataforma: "PS5",
    generos: ["Ação", "Sci-fi", "Hack and Slash"],
  },
  {
    nome: "Wuthering Waves",
    preco: 0.0,
    descricao: "RPG de ação gratuito com mundo aberto vibrante.",
    estoque: 100,
    desenvolvedora: "Kuro Games",
    dataLancamento: new Date("2024-12-10"),
    plataforma: "PC",
    generos: ["RPG", "Mundo Aberto", "Gratuito para jogar", "Ação"],
  },
];
